### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by haesleinhuepf** [fomightez/mini-pipelines#1]
Hi @fomightez ,

this is an amazing resource! Thanks for sharing openly! I was just wondering under which conditions one could reuse the tools and code provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by fomightez** [comment]
Thanks for the reminder. I added one.   
Most of my other recent repos have one. This one was sort of an earlier one. Mostly I use Snakemake these days for this type of idea.   
And a lot of my other repos do more useful things, usually taking advantage of MyBinder to at least offer a test environment, such as this one. Although that isn't a biology related one. [This one](https://github.com/fomightez/bendit-binder) is though.
